<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IlcInstructionSet>native</IlcInstructionSet>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>anycpu</PlatformTarget>
    <BaseOutputPath>../../bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="10.0.10"/>
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.10"/>
    <PackageReference Include="MySqlConnector" Version="2.6.1"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    <PackageReference Include="Npgsql" Version="10.0.3"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SatchSDKCore\SatchSDKCore.csproj"/>
  </ItemGroup>

</Project>
